/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Neo-Brutalism Dark Rose Palette (from HTML design)
        "on-background": "#e4e1e5",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "primary-fixed": "#ffdadb",
        "on-secondary-fixed": "#3f0016",
        "inverse-primary": "#be003c",
        "primary-container": "#c3073f",
        "inverse-surface": "#e4e1e5",
        "secondary-fixed": "#ffd9df",
        "surface-container-high": "#2a2a2d",
        "surface": "#131316",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb2bb",
        "background": "#131316",
        "on-tertiary": "#5d1425",
        "on-primary": "#67001d",
        "surface-container-lowest": "#0e0e11",
        "surface-bright": "#39393c",
        "surface-dim": "#131316",
        "on-secondary-container": "#ff96ad",
        "surface-container-low": "#1b1b1e",
        "on-primary-fixed-variant": "#91002c",
        "on-primary-fixed": "#40000e",
        "outline": "#ab888a",
        "on-tertiary-fixed": "#400012",
        "on-surface": "#e4e1e5",
        "on-error": "#690005",
        "tertiary": "#ffb2bb",
        "on-primary-container": "#ffd3d5",
        "primary-fixed-dim": "#ffb2b8",
        "tertiary-fixed": "#ffd9dd",
        "tertiary-container": "#9d4554",
        "surface-tint": "#ffb2b8",
        "surface-container": "#1f1f22",
        "on-surface-variant": "#e4bdbf",
        "outline-variant": "#5b4041",
        "on-secondary-fixed-variant": "#90003c",
        "secondary-container": "#90003c",
        "secondary-fixed-dim": "#ffb1c0",
        "on-tertiary-container": "#ffd3d7",
        "surface-variant": "#353438",
        "on-tertiary-fixed-variant": "#7b2b3b",
        "on-secondary": "#660029",
        "secondary": "#ffb1c0",
        "primary": "#ffb2b8",
        "inverse-on-surface": "#303033",
        "surface-container-highest": "#353438",
        // Custom shorthand colors
        "neutral-950": "#0a0a0a",
        "neutral-900": "#131316",
        "neutral-800": "#1a1a1d",
        "neutral-700": "#252528",
        "rose-700": "#c3073f",
        "rose-600": "#e03e5a",
        "rose-500": "#ff4d6d",
        "green-600": "#16a34a",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "xl": "48px",
        "margin": "32px",
        "xs": "4px",
        "sm": "8px",
        "lg": "24px",
        "gutter": "24px",
        "md": "16px",
        "unit": "4px",
      },
      fontFamily: {
        "h3": ["Space Grotesk"],
        "body-lg": ["Space Grotesk"],
        "label-caps": ["Space Grotesk"],
        "body-md": ["Space Grotesk"],
        "h1": ["Space Grotesk"],
        "h2": ["Space Grotesk"],
        "sans": ["Space Grotesk"],
        "mono": ["Space Grotesk"],
      },
      fontSize: {
        // Custom typography scale (increased by ~10-15%)
        "h3": ["36px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["20px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "label-caps": ["13px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-md": ["18px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "h1": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h2": ["56px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        // Override default Tailwind text utilities
        "xs": ["12px", { lineHeight: "1.4" }],
        "sm": ["14px", { lineHeight: "1.5" }],
        "base": ["16px", { lineHeight: "1.6" }],
        "lg": ["18px", { lineHeight: "1.6" }],
        "xl": ["20px", { lineHeight: "1.6" }],
        "2xl": ["24px", { lineHeight: "1.5" }],
        "3xl": ["30px", { lineHeight: "1.4" }],
        "4xl": ["36px", { lineHeight: "1.3" }],
      },
    },
  },
  plugins: [],
}
